@ECHO OFF
SETLOCAL ENABLEDELAYEDEXPANSION

sqlcmd -Snp:\\.\pipe\MSSQL$SQLEXPRESS\sql\query -d PIZZALOGISTICS -Q "EXEC SetupPizzaInformationStore"
sqlcmd -Snp:\\.\pipe\MSSQL$SQLEXPRESS\sql\query -d PIZZALOGISTICS -Q "EXEC BULKPIZZADATA_RAWIMPORT @FILENAME=$(IMPORTFILE)" -v IMPORTFILE=""
sqlcmd -Snp:\\.\pipe\MSSQL$SQLEXPRESS\sql\query -d PIZZALOGISTICS -Q "EXEC CUSTOMERLOAD"
sqlcmd -Snp:\\.\pipe\MSSQL$SQLEXPRESS\sql\query -d PIZZALOGISTICS -Q "EXEC MENULOAD"
sqlcmd -Snp:\\.\pipe\MSSQL$SQLEXPRESS\sql\query -d PIZZALOGISTICS -Q "EXEC ORDERSLOAD"
sqlcmd -Snp:\\.\pipe\MSSQL$SQLEXPRESS\sql\query -d PIZZALOGISTICS -Q "EXEC ORDEREDITEMSLOAD"
